config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, except: %i[new create]
  resources :timeline, only: %i[index new create destroy] do
    resources :reactions, only: %i[create destroy]
  end
  resources :tasks do
    member do
      patch :complete
      patch :incomplete
    end
  end
  resources :timers, only: [:index]
  get 'pomodoro/index'
  get 'dashboard/show'

  get 'reactions/create', to: 'reactions#create'
  get 'reactions/destroy', to: 'reactions#destroy'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :tasks, dependent: :destroy
  has_many :timeline_post, dependent: :destroy
  has_many :reactions, dependent: :destroy
  validates :username, presence: true
  validates :email, presence: true
  validates :password, confirmation: true, if: :password_required?
  def self.guest_user
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = 'ゲストユーザー'
    end
  end

  private

  def password_required?
    password.present? || password_confirmation.present?
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    before_action :protect_guest_user, only: %i[update destroy]

    def guest_sign_in
      user = User.guest_user
      sign_in user
      redirect_to dashboard_show_path(user.id), notice: 'ゲストユーザーとしてログインしました。'
    end

    def update; end

    def destroy; end

    private

    def protect_guest_user
      return unless current_user.guest?

      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]

  def show
    @user = if params[:id] == 'guest_sign_in'
              User.guest_user
            else
              User.find(params[:id])
            end
    @timeline_posts = @user.timeline_post.includes(:tasks, :images_attachments, :reactions).order(created_at: :desc)
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'プロフィールを更新しました。'
    else
      flash.now[:alert] = '更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_to root_path
  end

  private

  def set_user
    @user = params[:id] == 'guest_sign_in' ? User.guest_user : User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :profile_image)
  end
end

app/helpers/users/sessions_helper.rb
# frozen_string_literal: true

module Users
  module SessionsHelper
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<h1>アカウント設定</h1>
<div class="form">
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :username, "ユーザー名", class: "form-label" %>
      <%= f.text_field :username, class: "form-input #{'is-invalid' if @user.errors[:username].any?}" %>
      <% if @user.errors[:username].any? %>
        <div class="error-message">
          <%= @user.errors.full_messages_for(:username).join(", ") %>
        </div>
      <% end %>
    </div>
  
    <div class="form-group">
      <%= f.label :email, "メールアドレス", class: "form-label" %>
      <%= f.text_field :email, class: "form-input #{'is-invalid' if @user.errors[:email].any?}" %>
      <% if @user.errors[:email].any? %>
        <div class="error-message">
          <%= @user.errors.full_messages_for(:email).join(", ") %>
        </div>
      <% end %>
    </div>
  
    <div class="form-group">
      <%= f.label :profile_image, "プロフィール画像", class: "form-label" %>
      <%= f.file_field :profile_image, class: "form-input" %>
    </div>
    
    <div class="form-actions">
      <%= link_to "戻る", request.referer, class: "btn btn-secondary" %>
      <%= f.submit "更新する", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% if @user == User.guest_user %>
  <h1 class="page-title">ゲストユーザーのページ</h1>
  <p>ゲストユーザーとしてログイン中です。</p>
<% elsif @user.id == current_user.id %>
  <h1 class="page-title">マイページ</h1>
<% else %>
  <%= link_to "←戻る", timeline_index_path, class: "back-link" %>
  <h1 class="page-title">プロフィール</h1>
<% end %>
<div class="profile-container">
  <div class="profile-header">
  <%= image_tag @user.profile_image.attached? ? url_for(@user.profile_image) : asset_path("no_image.png"), class: "profile-image" %>
  <div class="profile-info">
      <h2 class="username"><%= @user.username == "ゲストユーザー" ? "ゲストユーザー" : @user.username %></h2>
      <% if @user.id == current_user.id %>
        <p class="email"><%= @user.email %></p>
        <div class="profile-actions">
          <%= link_to edit_user_path(@user), class: "btn btn-edit" do %>
            <i class="fa fa-pencil-alt"></i> 編集
          <% end %>
          <%= link_to user_path(@user), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-delete" do %>
            <i class="fa fa-trash-alt"></i> 削除
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<h1>投稿一覧</h1>
<% @timeline_posts.each do |post| %>
  <div class="timeline-post">
    <div class="post-header">
      <%= image_tag post.user.profile_image.attached? ? url_for(post.user.profile_image) : asset_path("no_image.png"), size: "50x50", class: "profile-img" %>
      <%= link_to post.user.username, user_path(post.user), class: "username-link" %>
      <% if post.user.id == current_user.id %>
        <%= link_to timeline_path(post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "delete-btn" do %>
          <i class="fa fa-trash"></i>
        <% end %>
      <% end %>
    </div>
    <div class="post-body">
      <p class="task-header">達成したタスク:</p>
      <ul class="task-list">
        <% post.tasks.each do |task| %>
          <li>・<%= task.content %></li>
        <% end %>
      </ul>
      <p class="comment-header">コメント: <span class="comment-content"><%= simple_format(post.content) %></span></p>
      <% if post.images.attached? %>
        <div class="attached-images">
          <p class="attached-title">添付画像:</p>
          <div class="image-gallery <%= 'single-image' if post.images.count == 1 %>">
            <% post.images.each do |image| %>
              <%= image_tag url_for(image), alt: "添付画像", class: "image" %>
            <% end %>
          </div>    
        </div>
      <% end %>
      <p class="post-time">投稿日時: <%= post.created_at.strftime("%Y/%m/%d %H:%M") %></p>
    </div>
    <div class="post-actions">
      <%= button_to timeline_reactions_path(post), method: :post, class: "reaction-btn" do %>
        <i class="fa fa-thumbs-up"></i> よく頑張ったね！
      <% end %>
      <span class="reaction-count">頑張ったね数: <%= post.reactions.count %></span>
    </div>
    <div class="reaction-list">
      <p class="reaction-header">頑張ったねした人:</p>
      <ul>
        <% post.reactions.includes(:user).group_by(&:user).each do |user, reactions| %>
          <li>
            <%= image_tag user.profile_image.attached? ? url_for(user.profile_image) : asset_path("no_image.png"), size: "20x20", class: "profile-img" %>
            <%= user.username %> <%= reactions.count %>回
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>